# Generated by Django 3.0.3 on 2020-04-02 11:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pays',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
