# Generated by Django 3.0.3 on 2020-04-02 12:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
