# Generated by Django 3.0.3 on 2020-03-23 10:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('cliks', models.PositiveIntegerField()),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('creation', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
