# Generated by Django 3.0.3 on 2020-03-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='cliks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
