# Generated by Django 3.0.3 on 2020-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200323_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='cliks',
            field=models.PositiveIntegerField(),
        ),
    ]
