# Generated by Django 3.0.3 on 2020-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200323_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='world',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliks', models.BigIntegerField(default=0)),
            ],
        ),
    ]
